# Generated by Django 3.1.2 on 2020-11-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulatorApp', '0002_strategy_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simulator',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('lengthOfTradingDay', models.DateTimeField()),
                ('productName', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='')),
                ('maxPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minPrice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marketOpen', models.BooleanField()),
            ],
        ),
    ]
