# Generated by Django 3.1.2 on 2020-11-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulatorApp', '0003_simulator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulator',
            name='lengthOfTradingDay',
            field=models.TimeField(),
        ),
    ]
