# Generated by Django 3.1.2 on 2020-11-18 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('simulatorApp', '0004_auto_20201118_1346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulator',
            old_name='id',
            new_name='ID',
        ),
    ]
