# Generated by Django 3.1.2 on 2020-11-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulatorApp', '0005_auto_20201118_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulator',
            name='lengthOfTradingDay',
            field=models.DurationField(),
        ),
    ]
