# Generated by Django 3.1.2 on 2020-11-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulatorApp', '0006_auto_20201118_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulator',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='simulator',
            name='lengthOfTradingDay',
            field=models.DurationField(default='01:00:00'),
        ),
    ]
