# Generated by Django 3.1.2 on 2020-11-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulatorApp', '0007_auto_20201118_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='simulator',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
