# Generated by Django 3.1.2 on 2021-02-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulatorApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priceeffects',
            name='high_sales',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=12),
        ),
        migrations.AlterField(
            model_name='priceeffects',
            name='low_sales',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=12),
        ),
        migrations.AlterField(
            model_name='priceeffects',
            name='med_sales',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=12),
        ),
    ]
