# Generated by Django 3.1.2 on 2021-01-27 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulatorApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_event_title', models.CharField(default='Market Event', max_length=256)),
                ('market_event_text', models.CharField(default='The market has changed, this means that consumer habits may also have changed.', max_length=5096)),
                ('simulator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulatorApp.simulator')),
            ],
        ),
        migrations.CreateModel(
            name='PolicyEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_cost', models.DecimalField(decimal_places=4, default=0.5, max_digits=12)),
                ('low_customer', models.DecimalField(decimal_places=4, default=1, max_digits=12)),
                ('low_sales', models.DecimalField(decimal_places=4, default=0.75, max_digits=12)),
                ('med_cost', models.DecimalField(decimal_places=4, default=1.0, max_digits=12)),
                ('med_customer', models.DecimalField(decimal_places=4, default=3, max_digits=12)),
                ('med_sales', models.DecimalField(decimal_places=4, default=1.0, max_digits=12)),
                ('high_cost', models.DecimalField(decimal_places=4, default=1.5, max_digits=12)),
                ('high_customer', models.DecimalField(decimal_places=4, default=2, max_digits=12)),
                ('high_sales', models.DecimalField(decimal_places=4, default=0.75, max_digits=12)),
                ('market_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulatorApp.marketevent')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulatorApp.policy')),
            ],
        ),
    ]
