# Generated by Django 3.1.2 on 2021-01-27 09:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('simulatorApp', '0002_marketevent_policyevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketevent',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='marketevent',
            name='valid_to',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
