# Generated by Django 3.1.2 on 2021-01-27 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulatorApp', '0003_auto_20210127_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceEffects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('boundary', models.SmallIntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1)),
                ('low_customers', models.IntegerField(default=1)),
                ('low_sales', models.IntegerField(default=1)),
                ('med_customers', models.IntegerField(default=1)),
                ('med_sales', models.IntegerField(default=1)),
                ('high_customers', models.IntegerField(default=1)),
                ('high_sales', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='price',
            name='price_effects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='simulatorApp.priceeffects'),
        ),
    ]
