# Generated by Django 3.1.2 on 2021-02-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulatorApp', '0007_auto_20210127_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulator',
            name='endQuizUrl',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='simulator',
            name='startQuizUrl',
            field=models.URLField(blank=True),
        ),
    ]
