# Generated by Django 3.1.2 on 2021-02-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulatorApp', '0008_auto_20210203_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='popupevent',
            name='is_quiz',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='popupevent',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='simulator',
            name='startQuizUrl',
            field=models.URLField(blank=True, default=''),
        ),
    ]
