# Generated by Django 3.1.2 on 2021-02-10 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulatorApp', '0009_auto_20210203_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronJobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cronjobid', models.CharField(max_length=128)),
            ],
        ),
    ]
