# Generated by Django 3.1.2 on 2021-02-10 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('simulatorApp', '0010_cronjobs'),
    ]

    operations = [
        migrations.CreateModel(
            name='DateCronJobs',
            fields=[
                ('cronjobs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simulatorApp.cronjobs')),
                ('run_date', models.DateTimeField()),
            ],
            bases=('simulatorApp.cronjobs',),
        ),
        migrations.AddField(
            model_name='cronjobs',
            name='replace_existing',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='CalculationCronJobs',
            fields=[
                ('cronjobs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simulatorApp.cronjobs')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('days', models.IntegerField(default=0)),
                ('hours', models.IntegerField(default=0)),
                ('minutes', models.IntegerField(default=0)),
                ('seconds', models.IntegerField(default=0)),
                ('simulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulatorApp.simulator')),
            ],
            bases=('simulatorApp.cronjobs',),
        ),
        migrations.CreateModel(
            name='SimulatorEndCronJobs',
            fields=[
                ('datecronjobs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simulatorApp.datecronjobs')),
                ('simulator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulatorApp.simulator')),
            ],
            bases=('simulatorApp.datecronjobs',),
        ),
        migrations.CreateModel(
            name='MarketEventCronJobs',
            fields=[
                ('datecronjobs_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='simulatorApp.datecronjobs')),
                ('market_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulatorApp.marketevent')),
            ],
            bases=('simulatorApp.datecronjobs',),
        ),
    ]
