"""
Django settings for BusinessSimulator project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""
import os
from pathlib import Path
KEY_FILE_EXISTS = False
try:
    from .key import Key
    KEY_FILE_EXISTS = True
except ModuleNotFoundError as err:
    try:
        from .BusinessSimulator.key import Key
        KEY_FILE_EXISTS = True
    except ModuleNotFoundError as err:
        print("Key file doesn't exist. Using Docker method.")

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# HTML templates directory
# All templates should be placed in this directory
# so they can be used by the views
TEMPLATE_DIR = os.path.join(BASE_DIR, "templates")

#set timezone
os.environ['tz'] = "Europe/London"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
if KEY_FILE_EXISTS:
    SECRET_KEY = Key.SECRET_KEY
else:
    SECRET_KEY = "sidhantbcosjaoijdowaijiwdhiehfpoifjoiewajoiweajp1234567u54321f9ife0i"
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sass_processor',
    'simulatorApp'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'BusinessSimulator.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_DIR],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'BusinessSimulator.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

if KEY_FILE_EXISTS:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'BusinessSimulator',
            'HOST': '127.0.0.1',
            'PORT': '3306',
            'USER': Key.MYSQL_USERNAME,
            'PASSWORD': Key.MYSQL_PASSWORD,
            'TEST': {
                'NAME': 'test_db', # the database django will use to run tests, make sure mysql user has create database permissions!
            },
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'django_app',
            'USER': 'django_app',
            'PASSWORD': 'django_app123',
            'HOST': 'db',
            'PORT': '3306',
            'OPTIONS': {'charset': 'utf8mb4'},
        }

    }


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files store: (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/
#
# Place any images, css or javascript we wish to use
# in the static dir, we can ignore staticfiles dir for now

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static'), ]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles/') #os.path.join(BASE_DIR, 'staticfiles')

# Incase of shit hitting the fan due to this malfunctioning, please refer to https://github.com/jrief/django-sass-processor
SASS_PROCESSOR_ROOT = STATIC_ROOT #os.path.join(, 'assets')

# STATICFILES_FINDERS = [
#     'django.contrib.staticfiles.finders.FileSystemFinder',
#     'django.contrib.staticfiles.finders.AppDirectoriesFinder',
#     'sass_processor.finders.CssFinder',
# ]


SASS_OUTPUT_STYLE = 'compressed'
